apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloWorld
  labels:
    name: helloWorld
spec:
  selector:
    matchLabels:
      name: myapp
  template:
    metadata:
      labels:
        name: myapp
    spec:
      containers:
        - name: myapp
          image: pz/demo
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
